server:
  port: 8090
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
     name: gateway-cloud
  cloud:
     gateway:
        routes: 
        - id: productModule
          uri: http://localhost:8085
          predicates: 
          - Path=/product/**
        - id: discountModule
          uri: http://localhost:8086
          predicates: 
          - Path=/discount/**